# Script de Inyeccion de datos
En este archivo, inyectamos los datos homologados y normalizados

### IMPORTACIONES DE BIBLIOTECAS NECESARIAS

In [2]:
import polars as pl
import sqlalchemy as sa
from IPython.display import display
from pydantic import BaseModel

### Constantes del Notebook
Aqui se definen las constantes que se necesiten para subir los archivos

In [39]:
FILE_PATH = './layouts/oferta_academicav2.2.xlsx'  # cambiar por ruta del archivo que se desea leer
SHEETS_NAMES = ['area', 'escuela', 'carrera', 'habilidad', "carrera_habilidad", "criterio"]  # nombre de las hojas que se desean procesar
DB_HOST = '100.95.220.1'
DB_PORT = 5432
DB_USER = 'admin'
DB_PASSWORD = "password"
DB_CONECTION = "athena"
DIR_SAVE = "load_data.sql"

### Modelos de pydantic

en este apartado estan los modelos para subir a la base de datos los datos correspondientes sin romper la tabla

In [12]:
class Area(BaseModel):
    id_area: int
    nombre_area: str

class Escuela(BaseModel):
    id_escuela: int
    nombre_escuela: str

class Carrera(BaseModel):
    id_carrera: int
    nombre_carrera: str
    id_area: int

class Habilidad(BaseModel):
    id_habilidad: int
    descripcion: str

class criterios(BaseModel):
    id_criterio: int
    descripcion: str
    id_habilidad: int

### Funciones de procesamiento

aqui estan todas las funciones para procesar el excel, dependiendo de la hoja lo procesa de manera distinta

In [37]:
class SQLGenerator:
    def carrera(self, df: pl.DataFrame) -> str:
        sql = "INSERT INTO carrera (id_carrera, nombre_carrera, id_area) VALUES "
        values = []
        for row in df.iter_rows(named=True):
            values.append(f"({row['id_carrera']}, '{row['nombre_carrera']}', {row['id_area']})")
        sql += ",\n".join(values) + ";"
        return sql

    def area(self, df: pl.DataFrame) -> str:
        sql = "INSERT INTO area (id_area, nombre_area) VALUES "
        values = []
        for row in df.iter_rows(named=True):
            values.append(f"({row['id_area']}, '{row['nombre_area']}')")
        sql += ",\n".join(values) + ";"
        return sql

    def escuela(self, df: pl.DataFrame) -> str:
        sql = "INSERT INTO escuela (id_escuela, nombre_escuela) VALUES "
        values = []
        for row in df.iter_rows(named=True):
            values.append(f"({row['id_escuela']}, '{row['nombre_escuela']}')")
        sql += ",\n".join(values) + ";"
        return sql

    def habilidad(self, df: pl.DataFrame) -> str:
        sql = "INSERT INTO habilidad (id_habilidad, descripcion) VALUES "
        values = []
        for row in df.iter_rows(named=True):
            values.append(f"({row['id_habilidad']}, '{row['descripcion']}')")
        sql += ",\n".join(values) + ";"
        return sql

    def carrera_habilidad(self, df: pl.DataFrame) -> str:
        sql = "INSERT INTO carrera_habilidad (id_carrera, id_habilidad) VALUES "
        values = []
        for row in df.iter_rows(named=True):
            values.append(f"({row['id_carrera']}, {row['id_habilidad']})")
        sql += ",\n".join(values) + ";"
        return sql

    def criterio(self, df: pl.DataFrame) -> str:
        sql = "INSERT INTO criterio (id_criterio, descripcion, id_habilidad) VALUES "
        values = []
        for row in df.iter_rows(named=True):
            values.append(f"({row['id_criterio']}, '{row['nombre_criterio']}', {row['id_habilidad']})")
        sql += ",\n".join(values) + ";"
        return sql

def db_conection():
    try:
        engine = sa.create_engine(f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_CONECTION}')
        print("Database connection successful.")
        return engine
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

def read_excel_file(file_path: str, sheet_name: str) -> pl.DataFrame:
    df_sheet = pl.read_excel(file_path, sheet_name=sheet_name)
    return df_sheet

def view_excel_sheets(df: pl.DataFrame, sheet_name: str):
    print(f"Sheet: {sheet_name}")
    display(df[:5])

def ask_submit_data(df: pl.DataFrame, sheet_name: str):
    SQLGen = SQLGenerator()
    sql_archive = getattr(SQLGen, sheet_name)(df)
    print(f"SQL for {sheet_name}:\n{sql_archive}")
    return sql_archive

def save_text_to_file(text: str, filename: str):
    with open(filename, 'w') as f:
        f.write(text)

### Ejecucion

aqui se ejecuta el script, haciendo que se procese y se suba la informacion

In [42]:
if __name__ == "__main__":
    sql_data = []
    for sheet_name in SHEETS_NAMES:
        df = read_excel_file(FILE_PATH, sheet_name)
        view_excel_sheets(df, sheet_name)
        sql_text = ask_submit_data(df, sheet_name)
        sql_data.append(sql_text)
    save_text_to_file("\n\n".join(sql_data), DIR_SAVE)

Sheet: area

/var/folders/5c/1h_2rjpj3wg1lps5yq7kg2740000gn/T/ipykernel_56357/3370824070.py:60: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df_sheet = pl.read_excel(file_path, sheet_name=sheet_name)

shape: (3, 2)
┌─────────┬─────────────────────────────────┐
│ id_area ┆ nombre_area                     │
│ ---     ┆ ---                             │
│ i64     ┆ str                             │
╞═════════╪═════════════════════════════════╡
│ 1       ┆ Ingeniería y Ciencias Físico M… │
│ 2       ┆ Ciencias Médico Biológicas      │
│ 3       ┆ Ciencias Sociales y Administra… │
└─────────┴─────────────────────────────────┘

SQL for area:
INSERT INTO area (id_area, nombre_area) VALUES (1, 'Ingeniería y Ciencias Físico Matemáticas'),
(2, 'Ciencias Médico Biológicas'),
(3, 'Ciencias Sociales y Administrativas');
Sheet: escuela

shape: (5, 2)
┌────────────┬─────────────────────────┐
│ id_escuela ┆ nombre_escuela          │
│ ---        ┆ ---                     │
│ i64        ┆ str                     │
╞════════════╪═════════════════════════╡
│ 1          ┆ CICS Unidad Milpa Alta  │
│ 2          ┆ CICS Unidad Santo Tomás │
│ 3          ┆ ENBA                    │
│ 4          ┆ ENCB                    │
│ 5          ┆ ENMyH                   │
└────────────┴─────────────────────────┘

SQL for escuela:
INSERT INTO escuela (id_escuela, nombre_escuela) VALUES (1, 'CICS Unidad Milpa Alta'),
(2, 'CICS Unidad Santo Tomás'),
(3, 'ENBA'),
(4, 'ENCB'),
(5, 'ENMyH'),
(6, 'ESCA Unidad Santo Tomás'),
(7, 'ESCA Unidad Tepepan'),
(8, 'ESCOM'),
(9, 'ESE'),
(10, 'ESEO'),
(11, 'ESFM'),
(12, 'ESIA Unidad Tecamachalco'),
(13, 'ESIA Unidad Ticomán'),
(14, 'ESIA Unidad Zacatenco'),
(15, 'ESIME Unidad Azcapotzalco '),
(16, 'ESIME Unidad Culhuacán'),
(17, 'ESIME Unidad Ticomán'),
(18, 'ESIME Unidad Zacatenco'),
(19, 'ESIQIE'),
(20, 'ESIT'),
(21, 'ESM'),
(22, 'EST'),
(23, 'UPIBI'),
(24, 'UPIEM'),
(25, 'UPIICSA'),
(26, 'UPIITA');
Sheet: carrera

shape: (5, 3)
┌────────────┬────────────────────────┬─────────┐
│ id_carrera ┆ nombre_carrera         ┆ id_area │
│ ---        ┆ ---                    ┆ ---     │
│ i64        ┆ str                    ┆ i64     │
╞════════════╪════════════════════════╪═════════╡
│ 1          ┆ Ingeniería Aeronáutica ┆ 1       │
│ 2          ┆ Ingeniería Ambiental   ┆ 1       │
│ 3          ┆ Ingeniería Biomédica   ┆ 1       │
│ 4          ┆ Ingeniería Biónica     ┆ 1       │
│ 5          ┆ Ingeniería Bioquímica  ┆ 1       │
└────────────┴────────────────────────┴─────────┘

SQL for carrera:
INSERT INTO carrera (id_carrera, nombre_carrera, id_area) VALUES (1, 'Ingeniería Aeronáutica', 1),
(2, 'Ingeniería Ambiental', 1),
(3, 'Ingeniería Biomédica', 1),
(4, 'Ingeniería Biónica', 1),
(5, 'Ingeniería Bioquímica', 1),
(6, 'Ingeniería Biotecnológica', 1),
(7, 'Ingeniería Civil', 1),
(8, 'Ingeniería Eléctrica', 1),
(9, 'Ingeniería en Alimentos', 1),
(10, 'Ingeniería en Computación', 1),
(11, 'Ingeniería en Comunicaciones y Electrónica', 1),
(12, 'Ingeniería en Control y Automatización', 1),
(13, 'Ingeniería en Energía', 1),
(14, 'Ingeniería en Informática', 1),
(15, 'Ingeniería en Inteligencia Artificial', 1),
(16, 'Ingeniería en Meteorología', 1),
(17, 'Ingeniería en Movilidad Urbana', 1),
(18, 'Ingeniería en Negocios Energéticos Sustentables', 1),
(19, 'Ingeniería en Robótica Industrial', 1),
(20, 'Ingeniería en Sistemas Ambientales', 1),
(21, 'Ingeniería en Sistemas Automotrices', 1),
(22, 'Ingeniería en Sistemas Computacionales', 1),
(23, 'Ingeniería en Sistemas Energéticos y Redes Inteligentes', 1),
(24, 'Ingeniería en Transporte', 1),
(25, 'Ingeniería Farmacéutica', 1),
(26, 'Ingeniería Ferroviaria', 1),
(27, 'Ingeniería Fotónica', 1),
(28, 'Ingeniería Geofísica', 1),
(29, 'Ingeniería Geológica', 1),
(30, 'Ingeniería Industrial', 1),
(31, 'Ingeniería Matemática', 1),
(32, 'Ingeniería Mecánica', 1),
(33, 'Ingeniería Mecatrónica', 1),
(34, 'Ingeniería Petrolera', 1),
(35, 'Ingeniería Química Industrial', 1),
(36, 'Ingeniería Química Petrolera', 1),
(37, 'Ingeniería Telemática', 1),
(38, 'Ingeniería Textil', 1),
(39, 'Ingeniería Topográfica y Fotogramétrica', 1),
(40, 'Licenciatura en Ciencia de Datos', 1),
(41, 'Licenciatura en Ciencias de la Informática', 1),
(42, 'Licenciatura en Física y Matemáticas', 1),
(43, 'Licenciatura en Matemática Algorítmica', 1),
(44, 'Químico Bacteriólogo Parasitólogo', 2),
(45, 'Licenciatura en Biología', 2),
(46, 'Licenciatura en Enfermería', 2),
(47, 'Licenciatura en Enfermería y Obstetricia', 2),
(48, 'Licenciatura en Nutrición', 2),
(49, 'Licenciatura en Odontología', 2),
(50, 'Licenciatura en Optometría', 2),
(51, 'Licenciatura en Psicología', 2),
(52, 'Licenciatura en Trabajo Social', 2),
(53, 'Médico Cirujano Homeópata', 2),
(54, 'Médico Cirujano Partero', 2),
(55, 'Quimico Farmacéutico Industrial', 2),
(56, 'Licenciatura en Administración Industrial', 3),
(57, 'Contador Público', 3),
(58, 'Licenciatura en Administración y Desarrollo Empresarial', 3),
(59, 'Licenciatura en Archivonomía', 3),
(60, 'Licenciatura en Biblioteconomía', 3),
(61, 'Licenciatura en Economía', 3),
(62, 'Licenciatura en Mercadotecnia Digital', 3),
(63, 'Licenciatura en Negocios Digitales', 3),
(64, 'Licenciatura en Negocios Internacionales', 3),
(65, 'Licenciatura en Relaciones Comerciales', 3),
(66, 'Licenciatura en Turismo', 3);
Sheet: habilidad

shape: (5, 2)
┌──────────────┬─────────────────────────────────┐
│ id_habilidad ┆ descripcion                     │
│ ---          ┆ ---                             │
│ i64          ┆ str                             │
╞══════════════╪═════════════════════════════════╡
│ 1            ┆ Diseño, construcción, mantenim… │
│ 2            ┆ Proyección y puesta en operaci… │
│ 3            ┆ Investigación, adaptación y de… │
│ 4            ┆ Planeación, dirección y gestió… │
│ 5            ┆ Aplicación de normatividad téc… │
└──────────────┴─────────────────────────────────┘

SQL for habilidad:
INSERT INTO habilidad (id_habilidad, descripcion) VALUES (1, 'Diseño, construcción, mantenimiento y operación de aeronaves y sistemas aeronáuticos'),
(2, 'Proyección y puesta en operación de plantas e infraestructura de soporte aéreo'),
(3, 'Investigación, adaptación y desarrollo de nuevas tecnologías aeronáuticas'),
(4, 'Planeación, dirección y gestión de empresas de mantenimiento y servicios aeronáuticos'),
(5, 'Aplicación de normatividad técnica, jurídica, ética y de seguridad aeronáutica'),
(6, 'Comunicación técnica oral y escrita en español e inglés'),
(7, 'Pensamiento analítico, lógico, crítico y creativo para la solución de problemas de ingeniería'),
(8, 'Extracción de conocimiento implícito, patrones y anomalías en grandes volúmenes de datos (Big Data)'),
(9, 'Aplicación de inteligencia artificial, aprendizaje de máquina (Machine Learning) y estadística avanzada'),
(10, 'Diseño y gestión de sistemas de bases de datos para toma de decisiones directivas'),
(11, 'Modelado matemático predictivo enfocado a negocios, salud, finanzas y ciencia'),
(12, 'Manejo de herramientas informáticas, software especializado y tecnologías de la información'),
(13, 'Gestión estratégica de tecnologías de información, arquitectura de software y ciberseguridad'),
(14, 'Gestión e innovación en cómputo en la nube, analítica de datos y comercio electrónico'),
(15, 'Desarrollo, implantación y dirección de soluciones informáticas de vanguardia'),
(16, 'Liderazgo en emprendimientos de productos y servicios informáticos'),
(17, 'Gestión, administración de proyectos, evaluación técnico-económica y estudios de factibilidad'),
(18, 'Planeación, diseño, proyección, construcción y mantenimiento de obras de infraestructura civil'),
(19, 'Operación, mantenimiento y administración de proyectos de construcción pública y privada'),
(20, 'Estudios geotécnicos, evaluación de riesgo geológico y planeación urbana sustentable'),
(21, 'Evaluación e implementación de criterios de desarrollo sustentable y energías renovables'),
(22, 'Trabajo en equipo multidisciplinario, colaborativo e interdisciplinario'),
(23, 'Liderazgo, ética profesional y responsabilidad social y ambiental'),
(24, 'Diseño, evaluación y administración de sistemas informáticos, hardware, software y redes'),
(25, 'Desarrollo en arquitectura de computadoras, sistemas operativos, interfaces y automatización'),
(26, 'Investigación, innovación, adaptación y desarrollo de nuevas tecnologías'),
(27, 'Interpretación y diseño de diagramas mecánicos, eléctricos, electrónicos y computacionales'),
(28, 'Diseño, construcción y mantenimiento de dispositivos y sistemas electrónicos y de comunicaciones'),
(29, 'Procesamiento de señales analógicas y digitales, sistemas acústicos y de radiocomunicación'),
(30, 'Proyección y puesta en operación de plantas de radiocomunicación, acústica y control'),
(31, 'Manejo de herramientas computacionales y matemáticas para modelado de señales'),
(32, 'Aplicación de normatividad técnica, jurídica, ambiental y de seguridad industrial'),
(33, 'Diseño, construcción y mantenimiento de sistemas de control automático e instrumentación industrial'),
(34, 'Proyección y puesta en operación de plantas industriales automatizadas'),
(35, 'Diseño, simulación, optimización y control de procesos industriales'),
(36, 'Diseño, operación, protección y mantenimiento de redes de potencia y sistemas eléctricos'),
(37, 'Proyección de ingeniería conceptual y básica para generación y electrificación'),
(38, 'Manejo de instrumental especializado de laboratorio en pruebas eléctricas'),
(39, 'Diseño, planeación e innovación de tecnologías para aprovechamiento de recursos energéticos limpios'),
(40, 'Implementación de tecnologías de bajo impacto ambiental y eficiencia energética'),
(41, 'Operación e innovación de sistemas energéticos en los sectores público y privado'),
(42, 'Diagnóstico, diseño, dimensionamiento, gestión y operación de sistemas de transporte ferroviario'),
(43, 'Evaluación de impactos ambientales, urbanos, viales y peritajes en infraestructura férrea'),
(44, 'Realización de dictámenes técnicos y peritajes en sistemas ferroviarios'),
(45, 'Investigación básica y aplicada, modelado teórico y resolución de problemas complejos en física y matemáticas'),
(46, 'Análisis de situaciones complejas y desarrollo de soluciones científicas originales'),
(47, 'Desarrollo tecnológico y asesoría técnica a instituciones científicas e industriales'),
(48, 'Docencia e instrucción especializada en educación media superior y superior'),
(49, 'Conceptualización, diseño y fabricación de sistemas ópticos, fotónicos e integración optomecánica'),
(50, 'Aplicación de láseres, fuentes de luz, fibra óptica y seguridad en radiación óptica'),
(51, 'Análisis de viabilidad, gestión, operación y mantenimiento de proyectos fotónicos'),
(52, 'Manejo de instrumentos de laboratorio de alta precisión y herramientas optomecánicas'),
(53, 'Planeación, adquisición, procesamiento e interpretación de datos geofísicos para exploración del subsuelo'),
(54, 'Diseño de modelos numéricos para evaluación de acuíferos, minerales e hidrocarburos'),
(55, 'Uso de instrumentación geofísica y herramientas computacionales de vanguardia'),
(56, 'Exploración, cuantificación, evaluación y explotación de recursos minerales, hídricos, petroleros y geotérmicos'),
(57, 'Estudios geotécnicos para obras de ingeniería civil y delimitación de asentamientos humanos'),
(58, 'Evaluación de riesgos geológicos (volcánico, sísmico, deslaves) y caracterización de suelos'),
(59, 'Manejo e interpretación de bases de datos con enfoque geoestadístico y software especializado'),
(60, 'Análisis, diseño e implementación de sistemas inteligentes mediante algoritmos de IA'),
(61, 'Desarrollo en procesamiento de lenguaje natural, visión artificial y modelos bioinspirados'),
(62, 'Desarrollo colaborativo de soluciones en ciudades inteligentes, automatización y biometría'),
(63, 'Dirección, planeación y optimización de la productividad, calidad, logística y cadenas de suministro'),
(64, 'Integración de tecnologías inteligentes, manufactura avanzada y diseño de procesos operativos'),
(65, 'Diseño y realización de experimentos en productos, procesos e ingeniería de proyectos de inversión'),
(66, 'Manejo e interpretación de datos, bioestadística y modelos matemáticos predictivos'),
(67, 'Desarrollo e implementación de software de alta calidad vinculado con Internet de las Cosas (IoT)'),
(68, 'Gestión de la Seguridad de la Información, Analítica de Datos y Cómputo en la Nube'),
(69, 'Dirección de proyectos tecnológicos interdisciplinarios, consultoría y emprendimiento'),
(70, 'Planteamiento y solución algorítmica de problemas matemáticos mediante programación avanzada (Python, R, MATLAB)'),
(71, 'Análisis de datos masivos, redes neuronales, modelos estocásticos y trading algorítmico'),
(72, 'Desarrollo de modelos matemáticos para finanzas cuantitativas, optimización y simulación'),
(73, 'Redacción científico-técnica y composición de textos académicos'),
(74, 'Análisis de problemas reales, creación, solución e interpretación de modelos matemáticos representativos'),
(75, 'Uso y desarrollo de herramientas computacionales para solución de ecuaciones complejas'),
(76, 'Administración de recursos, elaboración de estudios de factibilidad y toma de decisiones'),
(77, 'Facilitación del diálogo e integración en grupos interdisciplinarios'),
(78, 'Diseño, fabricación, innovación y mantenimiento de máquinas, sistemas mecánicos y térmicos'),
(79, 'Proyección, puesta en marcha y operación de plantas e industrias metal-mecánicas'),
(80, 'Optimización del aprovechamiento de diversos tipos de energía en la industria'),
(81, 'Creación y dirección de micro, pequeñas y medianas empresas metal-mecánicas'),
(82, 'Diseño, gestión e integración de sistemas mecatrónicos (mecanismos, electrónica y software)'),
(83, 'Desarrollo de hardware y software para control, automatización y manufactura asistida por computadora (CAD/CAM/CAE)'),
(84, 'Integración de componentes electrónicos, sensores y actuadores en sistemas inteligentes'),
(85, 'Modelado de sistemas físicos, planteamiento de hipótesis y validación experimental'),
(86, 'Obtención, procesamiento e interpretación de datos atmosféricos mediante sensores, radares y satélites'),
(87, 'Elaboración de pronósticos meteorológicos, predicción numérica y emisión de alertas de protección civil'),
(88, 'Desarrollo de software y modelos informáticos para procesamiento de datos atmosféricos y SIG'),
(89, 'Planeación, diseño, evaluación y operación de sistemas de movilidad urbana sustentable'),
(90, 'Articulación de soluciones de transporte de personas y mercancías en dimensiones territorial y económica'),
(91, 'Evaluación de proyectos de infraestructura de transporte e impacto social y ambiental'),
(92, 'Manejo de software de procesamiento de datos, hojas de cálculo y herramientas gráficas'),
(93, 'Diseño, evaluación y gestión de modelos de negocio y proyectos en el sector energético'),
(94, 'Evaluación de eficiencia energética y gestión sustentable mediante análisis de ciclo de vida'),
(95, 'Diseño de estrategias técnico-económicas para aprovechamiento de fuentes renovables'),
(96, 'Desarrollo de habilidades directivas, comunicación efectiva y negociación'),
(97, 'Dirección de procesos de explotación y extracción de hidrocarburos, agua y energía geotérmica'),
(98, 'Diseño, programación, supervisión y mantenimiento de pozos petroleros e instalaciones de producción'),
(99, 'Cuantificación de reservas, caracterización de yacimientos y simulación numérica'),
(100, 'Elaboración de análisis económico, licitación y factibilidad de proyectos hidrocarburíferos'),
(101, 'Diseño, operación, simulación y administración de plantas químicas e industriales sustentables'),
(102, 'Evaluación de operaciones unitarias implicadas en la transformación de la materia'),
(103, 'Simulación, modelado y optimización de procesos químicos mediante software especializado'),
(104, 'Aplicación de sistemas de gestión de calidad, seguridad e higiene industrial'),
(105, 'Diseño, operación y optimización de plantas de refinación de petróleo y procesamiento de gas natural'),
(106, 'Muestreo, caracterización, control de calidad y tratamiento de hidrocarburos y derivados'),
(107, 'Tratamiento estadístico de datos de proceso y uso de simuladores industriales'),
(108, 'Programación y supervisión de medidas de seguridad industrial y control de contaminantes'),
(109, 'Diseño, fabricación y mantenimiento de celdas robóticas, sistemas automatizados y equipos de producción'),
(110, 'Proyección y puesta en operación de plantas e islas de manufactura robotizadas'),
(111, 'Investigación e implementación de nuevas tecnologías de automatización y lenguajes de programación'),
(112, 'Diseño, integración, prueba y mantenimiento de sistemas automotrices (propulsión, transmisión, chasis y seguridad)'),
(113, 'Manejo y simulación con herramientas de ingeniería y diseño asistido por computadora para el sector automotriz'),
(114, 'Planeación, dirección y ejecución de proyectos de ingeniería experimental automotriz'),
(115, 'Organización y supervisión de mantenimiento y producción industrial en la cadena automotriz'),
(116, 'Modelado, diseño, desarrollo e implementación de sistemas de software y hardware con estándares de calidad'),
(117, 'Diseño de algoritmos eficientes y estructuras de datos optimizadas'),
(118, 'Implementación de arquitecturas de software, sistemas distribuidos, protocolos de red y bases de datos'),
(119, 'Dirección y liderazgo de equipos de trabajo tecnológicos multidisciplinarios'),
(120, 'Diseño, construcción, monitoreo y gestión de redes eléctricas inteligentes (Smart Grids) y generación distribuida'),
(121, 'Optimización de recursos energéticos del lado de la demanda y mejoramiento de calidad energética'),
(122, 'Implementación de soluciones de ciberseguridad en infraestructura energética'),
(123, 'Diseño, desarrollo, administración y operación de redes de telecomunicaciones alámbricas e inalámbricas'),
(124, 'Procesamiento de datos, voz, video, cómputo ubicuo y desarrollo de aplicaciones telemáticas'),
(125, 'Empleo de protocolos de comunicación para transmisión segura de datos'),
(126, 'Instalación y gestión de sistemas de bases de datos y sistemas operativos'),
(127, 'Identificación, evaluación, transformación y control de calidad de fibras, hilos, tejidos y prendas'),
(128, 'Diseño, operación y optimización de procesos químicos de tintura, estampado y acabado textil'),
(129, 'Aplicación de estudios de tiempos y movimientos, metrología y ensayos de calidad textil'),
(130, 'Planeación, diseño y ejecución de levantamientos topográficos, geodésicos y fotogramétricos de alta precisión'),
(131, 'Procesamiento digital de imágenes, modelos digitales de terreno y gestión de Sistemas de Información Geográfica (SIG)'),
(132, 'Operación de equipo topográfico y geodésico de precisión para catastro y planeación urbana'),
(133, 'Diagnóstico, diseño, gestión, operación y evaluación de sistemas de transporte multimotriz'),
(134, 'Aplicación de tecnologías para simulación, planeación logística y control de flotas de transporte'),
(135, 'Análisis del impacto ambiental, económico, político y social del transporte'),
(136, 'Gestión y optimización de flotas, logística e infraestructura de transporte'),
(137, 'Diseño y desarrollo de análogos biológicos, dispositivos artificiales y sistemas biomiméticos'),
(138, 'Aplicación de principios biomiméticos para la solución de problemas de ingeniería'),
(139, 'Modelado matemático y simulación de variables biológicas y dinámicas'),
(140, 'Uso de bioestadística, matemáticas avanzadas y cálculo en desarrollo biónico'),
(141, 'Diseño, localización, instalación y puesta en marcha de plantas procesadoras de alimentos'),
(142, 'Supervisión, control e inocuidad en almacenamiento, conservación y distribución de alimentos'),
(143, 'Utilización de técnicas de simulación para desarrollo y escalamiento de productos alimenticios'),
(144, 'Evaluación de la calidad de materias primas, insumos y productos terminados'),
(145, 'Diseño de sistemas de prevención, minimización y control de contaminantes en aire, agua y suelo'),
(146, 'Diseño y operación de plantas de tratamiento de aguas y manejo de residuos sólidos y peligrosos'),
(147, 'Optimización y adaptación de tecnologías para diagnóstico y restauración de sitios contaminados'),
(148, 'Evaluación e implementación del uso de energías alternas para conservación ambiental'),
(149, 'Selección y desarrollo de métodos para diagnóstico microbiológico, clínico y parasitológico'),
(150, 'Producción y control integral de productos biológicos, vacunas y biotecnológicos'),
(151, 'Manejo de microorganismos en condiciones asépticas y bioseguridad ambiental y clínica'),
(152, 'Análisis de relaciones ecológicas microbianas para restauración y biorremediación'),
(153, 'Manejo, conservación y aprovechamiento sustentable de recursos bióticos y biodiversidad'),
(154, 'Evaluaciones de impacto ambiental, auditorías e implementación de acciones de mitigación'),
(155, 'Curaduría y gestión de colecciones biológicas científicas y catálogos de recursos naturales'),
(156, 'Análisis de procesos evolutivos, genéticos, biotecnológicos y salud ambiental'),
(157, 'Diseño, desarrollo, mantenimiento y administración de equipos e instrumentos médicos hospitalarios'),
(158, 'Selección, conservación y desarrollo de biomateriales, prótesis y órtesis'),
(159, 'Generación de criterios de planeación, normatividad e infraestructura hospitalaria'),
(160, 'Gestión tecnológica y dirección de proyectos en ingeniería clínica e investigación médica'),
(161, 'Aislamiento, purificación, cultivo y propagación de microorganismos de interés industrial'),
(162, 'Diseño, desarrollo, operación y optimización de bioprocesos para producción y recuperación de bioproductos'),
(163, 'Análisis e inspección de muestras mediante técnicas físico-químicas e instrumentales avanzadas'),
(164, 'Diseño y control de bioprocesos de tratamiento de efluentes y bioingeniería ambiental'),
(165, 'Aplicación de biotecnología en los sectores agropecuario, industrial, petrolero y ambiental'),
(166, 'Producción biotecnológica de vacunas, medicamentos, alimentos fermentados y propagación vegetal'),
(167, 'Atención médica integral, prevención, diagnóstico y tratamiento con enfoque de medicina general y homeopatía'),
(168, 'Investigación de problemas de salud pública y desarrollo asistencial humanitario'),
(169, 'Relación médico-paciente ética, responsable y solidaria con sectores desprotegidos'),
(170, 'Diagnóstico clínico, tratamiento y atención preventiva y curativa en medicina general y quirúrgica ambulatoria'),
(171, 'Atención del embarazo, parto, puerperio y programas prioritarios de salud pública'),
(172, 'Manejo farmacológico, interpretación de estudios de laboratorio e imagenología médica'),
(173, 'Compromiso ético, humanístico, de bioética y legalidad en el ejercicio de la medicina'),
(174, 'Cuidado integral de enfermería y atención de salud reproductiva y perinatal'),
(175, 'Fomento del autocuidado, estilos de vida saludables y educación para la salud'),
(176, 'Aplicación del método enfermero en el primer, segundo y tercer nivel de atención'),
(177, 'Sensibilidad social, ética humanística y liderazgo en el cuidado de la salud'),
(178, 'Aplicación del método enfermero en la promoción, prevención y recuperación de la salud'),
(179, 'Diagnóstico, planeación y ejecución de intervenciones de cuidado holístico'),
(180, 'Administración estratégica de servicios de enfermería e investigación clínica'),
(181, 'Actitud ética, humanística, de liderazgo y respeto a los derechos humanos'),
(182, 'Diseño, desarrollo, operación y optimización de bioprocesos para la producción de medicamentos'),
(183, 'Aplicación de procesos de purificación y formulación farmacéutica para uso humano'),
(184, 'Aplicación de conocimientos emergentes en proteómica, genómica, metabólica y nanobiotecnología'),
(185, 'Diseño, producción y control de calidad de sistemas de entrega de fármacos y medicamentos'),
(186, 'Atención en farmacia industrial, hospitalaria e investigación científica farmacéutica'),
(187, 'Gestión de calidad y cumplimiento de buenas prácticas de fabricación (GMP)'),
(188, 'Evaluación del estado nutricio, diagnóstico y cálculo dietoterapéutico individual y comunitario'),
(189, 'Planeación, administración y evaluación de programas de alimentación y nutrición aplicada'),
(190, 'Dirección y control de calidad sanitaria en servicios institucionales de alimentos'),
(191, 'Educación y orientación alimentaria en los diversos grupos de edad'),
(192, 'Promoción, prevención, diagnóstico y rehabilitación integral de la salud bucodental'),
(193, 'Operatoria dental, endodoncia, exodoncia, prótesis, ortodoncia y cirugía bucal'),
(194, 'Manejo de materiales dentales, bioseguridad y radiología intraoral'),
(195, 'Desarrollo de proyectos de investigación clínica y epidemiológica en odontología'),
(196, 'Evaluación, diagnóstico y tratamiento de alteraciones refractivas y salud visual'),
(197, 'Prescripción y adaptación de ayudas ópticas, lentes de contacto y terapia visual'),
(198, 'Diseño y ejecución de campañas de salud visual y diagnóstico epidemiológico ocular'),
(199, 'Manejo de instrumental optométrico e integración de ciencias biomédicas'),
(200, 'Evaluación de estados psicológicos, personalidad y competencias cognitivas y emocionales'),
(201, 'Prevención y tratamiento de alteraciones psicológicas en clínica, educación y organizaciones'),
(202, 'Promoción del bienestar psicológico individual, grupal y comunitario'),
(203, 'Investigación científica del comportamiento humano y procesos bio-psico-sociales'),
(204, 'Diagnóstico de vulnerabilidad ambiental y auditoría de riesgos ocupacionales e industriales'),
(205, 'Diseño y operación de plantas de tratamiento de agua y acondicionamiento hídrico'),

shape: (5, 2)
┌────────────┬──────────────┐
│ id_carrera ┆ id_habilidad │
│ ---        ┆ ---          │
│ i64        ┆ i64          │
╞════════════╪══════════════╡
│ 1          ┆ 1            │
│ 1          ┆ 2            │
│ 1          ┆ 3            │
│ 1          ┆ 4            │
│ 1          ┆ 5            │
└────────────┴──────────────┘

SQL for carrera_habilidad:
INSERT INTO carrera_habilidad (id_carrera, id_habilidad) VALUES (1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(2, 7),
(2, 8),
(2, 9),
(2, 10),
(2, 11),
(2, 12),
(3, 6),
(3, 13),
(3, 14),
(3, 15),
(3, 16),
(3, 17),
(4, 18),
(4, 19),
(4, 20),
(4, 21),
(4, 22),
(4, 23),
(5, 12),
(5, 22),
(5, 24),
(5, 25),
(5, 26),
(5, 27),
(6, 28),
(6, 29),
(6, 30),
(6, 31),
(6, 32),
(7, 7),
(7, 21),
(7, 33),
(7, 34),
(7, 35),
(8, 23),
(8, 35),
(8, 36),
(8, 37),
(8, 38),
(9, 17),
(9, 21),
(9, 39),
(9, 40),
(9, 41),
(10, 22),
(10, 23),
(10, 42),
(10, 43),
(10, 44),
(11, 7),
(11, 45),
(11, 46),
(11, 47),
(11, 48),
(12, 26),
(12, 49),
(12, 50),
(12, 51),
(12, 52),
(13, 20),
(13, 21),
(13, 53),
(13, 54),
(13, 55),
(14, 23),
(14, 56),
(14, 57),
(14, 58),
(14, 59),
(15, 9),
(15, 12),
(15, 60),
(15, 61),
(15, 62),
(16, 23),
(16, 63),
(16, 64),
(16, 65),
(16, 66),
(17, 6),
(17, 26),
(17, 67),
(17, 68),
(17, 69),
(18, 7),
(18, 70),
(18, 71),
(18, 72),
(18, 73),
(19, 45),
(19, 74),
(19, 75),
(19, 76),
(19, 77),
(20, 35),
(20, 78),
(20, 79),
(20, 80),
(20, 81),
(21, 35),
(21, 82),
(21, 83),
(21, 84),
(21, 85),
(22, 6),
(22, 21),
(22, 86),
(22, 87),
(22, 88),
(23, 23),
(23, 89),
(23, 90),
(23, 91),
(23, 92),
(24, 17),
(24, 93),
(24, 94),
(24, 95),
(24, 96),
(25, 32),
(25, 97),
(25, 98),
(25, 99),
(25, 100),
(26, 35),
(26, 101),
(26, 102),
(26, 103),
(26, 104),
(27, 35),
(27, 105),
(27, 106),
(27, 107),
(27, 108),
(28, 27),
(28, 35),
(28, 109),
(28, 110),
(28, 111),
(29, 22),
(29, 112),
(29, 113),
(29, 114),
(29, 115),
(30, 12),
(30, 116),
(30, 117),
(30, 118),
(30, 119),
(31, 17),
(31, 21),
(31, 120),
(31, 121),
(31, 122),
(32, 6),
(32, 123),
(32, 124),
(32, 125),
(32, 126),
(33, 23),
(33, 35),
(33, 127),
(33, 128),
(33, 129),
(34, 17),
(34, 22),
(34, 130),
(34, 131),
(34, 132),
(35, 23),
(35, 133),
(35, 134),
(35, 135),
(35, 136),
(36, 26),
(36, 137),
(36, 138),
(36, 139),
(36, 140),
(37, 35),
(37, 141),
(37, 142),
(37, 143),
(37, 144),
(38, 23),
(38, 145),
(38, 146),
(38, 147),
(38, 148),
(39, 32),
(39, 149),
(39, 150),
(39, 151),
(39, 152),
(40, 23),
(40, 153),
(40, 154),
(40, 155),
(40, 156),
(41, 22),
(41, 157),
(41, 158),
(41, 159),
(41, 160),
(42, 35),
(42, 161),
(42, 162),
(42, 163),
(42, 164),
(43, 6),
(43, 26),
(43, 162),
(43, 165),
(43, 166),
(44, 22),
(44, 23),
(44, 167),
(44, 168),
(44, 169),
(45, 22),
(45, 170),
(45, 171),
(45, 172),
(45, 173),
(46, 22),
(46, 174),
(46, 175),
(46, 176),
(46, 177),
(47, 22),
(47, 178),
(47, 179),
(47, 180),
(47, 181),
(48, 6),
(48, 17),
(48, 182),
(48, 183),
(48, 184),
(49, 23),
(49, 26),
(49, 185),
(49, 186),
(49, 187),
(50, 23),
(50, 188),
(50, 189),
(50, 190),
(50, 191),
(51, 23),
(51, 192),
(51, 193),
(51, 194),
(51, 195),
(52, 23),
(52, 196),
(52, 197),
(52, 198),
(52, 199),
(53, 22),
(53, 200),
(53, 201),
(53, 202),
(53, 203),
(54, 21),
(54, 145),
(54, 204),
(54, 205),
(54, 206),
(55, 22),
(55, 207),
(55, 208),
(55, 209),
(55, 210),
(56, 17),
(56, 211),
(56, 212),
(56, 213),
(56, 214),
(57, 23),
(57, 214),
(57, 215),
(57, 216),
(57, 217),
(58, 23),
(58, 218),
(58, 219),
(58, 220),
(58, 221),
(59, 23),
(59, 222),
(59, 223),
(59, 224),
(59, 225),
(60, 23),
(60, 226),
(60, 227),
(60, 228),
(60, 229),
(61, 23),
(61, 230),
(61, 231),
(61, 232),
(61, 233),
(62, 214),
(62, 234),
(62, 235),
(62, 236),
(62, 237),
(63, 214),
(63, 238),
(63, 239),
(63, 240),
(63, 241),
(64, 17),
(64, 242),
(64, 243),
(64, 244),
(64, 245),
(65, 214),
(65, 246),
(65, 247),
(65, 248),
(65, 249),
(66, 23),
(66, 250),
(66, 251),
(66, 252),
(66, 253);
Sheet: criterio

shape: (5, 3)
┌─────────────┬─────────────────┬──────────────┐
│ id_criterio ┆ nombre_criterio ┆ id_habilidad │
│ ---         ┆ ---             ┆ ---          │
│ i64         ┆ str             ┆ i64          │
╞═════════════╪═════════════════╪══════════════╡
│ 1           ┆ Diseño          ┆ 1            │
│ 2           ┆ Construcción    ┆ 1            │
│ 3           ┆ Mantenimiento   ┆ 1            │
│ 4           ┆ Proyección      ┆ 2            │
│ 5           ┆ Puesta          ┆ 2            │
└─────────────┴─────────────────┴──────────────┘

SQL for criterio:
INSERT INTO criterio (id_criterio, descripcion, id_habilidad) VALUES (1, 'Diseño', 1),
(2, 'Construcción', 1),
(3, 'Mantenimiento', 1),
(4, 'Proyección', 2),
(5, 'Puesta', 2),
(6, 'Operación de plantas', 2),
(7, 'Investigación', 3),
(8, 'Adaptación', 3),
(9, 'Desarrollo', 3),
(10, 'Planeación', 4),
(11, 'Dirección', 4),
(12, 'Gestión de empresas', 4),
(13, 'Aplicación de normatividad', 5),
(14, 'Jurídica', 5),
(15, 'Seguridad aeronáutica', 5),
(16, 'Comunicación técnica oral', 6),
(17, 'Escrita', 6),
(18, 'Español', 6),
(19, 'Pensamiento analítico', 7),
(20, 'Lógico', 7),
(21, 'Crítico', 7),
(22, 'Extracción de conocimiento', 8),
(23, 'Patrones', 8),
(24, 'Anomalías', 8),
(25, 'Aplicación de inteligencia', 9),
(26, 'Aprendizaje de máquina', 9),
(27, 'Estadística avanzada', 9),
(28, 'Gestión de sistemas', 10),
(29, 'Toma de decisiones', 10),
(30, 'Bases de datos', 10),
(31, 'Modelado matemático predictivo', 11),
(32, 'Finanzas', 11),
(33, 'Ciencia', 11),
(34, 'Manejo de herramientas', 12),
(35, 'Software especializado', 12),
(36, 'Tecnologías', 12),
(37, 'Gestión estratégica', 13),
(38, 'Arquitectura de software', 13),
(39, 'Ciberseguridad', 13),
(40, 'Gestión', 14),
(41, 'Innovación', 14),
(42, 'Cómputo', 14),
(43, 'Implantación', 15),
(44, 'Dirección de soluciones', 15),
(45, 'Informáticas de vanguardia', 15),
(46, 'Liderazgo', 16),
(47, 'Emprendimientos de productos', 16),
(48, 'Servicios informáticos', 16),
(49, 'Administración de proyectos', 17),
(50, 'Evaluación técnico-económica', 17),
(51, 'Estudios de factibilidad', 17),
(52, 'Mantenimiento de obras', 18),
(53, 'Infraestructura civil', 18),
(54, 'Operación', 19),
(55, 'Privada', 19),
(56, 'Construcción pública', 19),
(57, 'Estudios geotécnicos', 20),
(58, 'Evaluación de riesgo', 20),
(59, 'Planeación urbana sustentable', 20),
(60, 'Evaluación', 21),
(61, 'Implementación de criterios', 21),
(62, 'Energías renovables', 21),
(63, 'Trabajo', 22),
(64, 'Equipo multidisciplinario', 22),
(65, 'Colaborativo', 22),
(66, 'Ética profesional', 23),
(67, 'Responsabilidad social', 23),
(68, 'Ambiental', 23),
(69, 'Administración de sistemas', 24),
(70, 'Hardware', 24),
(71, 'Software', 24),
(72, 'Arquitectura de computadoras', 25),
(73, 'Sistemas operativos', 25),
(74, 'Interfaces', 25),
(75, 'Nuevas tecnologías', 26),
(76, 'Gestión de investigación', 26),
(77, 'Interpretación', 27),
(78, 'Diseño de diagramas', 27),
(79, 'Eléctricos', 27),
(80, 'Mantenimiento de dispositivos', 28),
(81, 'Sistemas electrónicos', 28),
(82, 'Comunicaciones', 28),
(83, 'Procesamiento de señales', 29),
(84, 'Digitales', 29),
(85, 'Sistemas acústicos', 29),
(86, 'Acústica', 30),
(87, 'Control', 30),
(88, 'Puesta en operación', 30),
(89, 'Matemáticas', 31),
(90, 'Modelado de señales', 31),
(91, 'Matemáticas para modelado', 31),
(92, 'Seguridad industrial', 32),
(93, 'Normatividad técnica', 32),
(94, 'Mantenimiento de sistemas', 33),
(95, 'Instrumentación industrial', 33),
(96, 'Control automático', 33),
(97, 'Plantas industriales', 34),
(98, 'Gestión de proyección', 34),
(99, 'Simulación', 35),
(100, 'Optimización', 35),
(101, 'Control de procesos', 35),
(102, 'Protección', 36),
(103, 'Mantenimiento de redes', 36),
(104, 'Sistemas eléctricos', 36),
(105, 'Proyección de ingeniería', 37),
(106, 'Básica', 37),
(107, 'Generación', 37),
(108, 'Manejo de instrumental', 38),
(109, 'Pruebas eléctricas', 38),
(110, 'Especializado de laboratorio', 38),
(111, 'Innovación de tecnologías', 39),
(112, 'Aprovechamiento de recursos', 39),
(113, 'Recursos energéticos', 39),
(114, 'Implementación de tecnologías', 40),
(115, 'Eficiencia energética', 40),
(116, 'Bajo impacto', 40),
(117, 'Innovación de sistemas', 41),
(118, 'Sectores público', 41),
(119, 'Privado', 41),
(120, 'Diagnóstico', 42),
(121, 'Dimensionamiento', 42),
(122, 'Operación de sistemas', 42),
(123, 'Evaluación de impactos', 43),
(124, 'Urbanos', 43),
(125, 'Viales', 43),
(126, 'Realización de dictámenes', 44),
(127, 'Peritajes', 44),
(128, 'Sistemas ferroviarios', 44),
(129, 'Investigación básica', 45),
(130, 'Aplicada', 45),
(131, 'Modelado teórico', 45),
(132, 'Análisis de situaciones', 46),
(133, 'Desarrollo de soluciones', 46),
(134, 'Situaciones complejas', 46),
(135, 'Desarrollo tecnológico', 47),
(136, 'Asesoría técnica', 47),
(137, 'Industriales', 47),
(138, 'Docencia', 48),
(139, 'Instrucción especializada', 48),
(140, 'Educación media superior', 48),
(141, 'Conceptualización', 49),
(142, 'Fabricación de sistemas', 49),
(143, 'Fotónicos', 49),
(144, 'Aplicación de láseres', 50),
(145, 'Fuentes de luz', 50),
(146, 'Fibra óptica', 50),
(147, 'Análisis de viabilidad', 51),
(148, 'Mantenimiento de proyectos', 51),
(149, 'Proyectos fotónicos', 51),
(150, 'Manejo de instrumentos', 52),
(151, 'Herramientas optomecánicas', 52),
(152, 'Laboratorio', 52),
(153, 'Adquisición', 53),
(154, 'Procesamiento', 53),
(155, 'Interpretación de datos', 53),
(156, 'Diseño de modelos', 54),
(157, 'Evaluación de acuíferos', 54),
(158, 'Minerales', 54),
(159, 'Uso de instrumentación', 55),
(160, 'Herramientas computacionales', 55),
(161, 'Computacionales de vanguardia', 55),
(162, 'Exploración', 56),
(163, 'Cuantificación', 56),
(164, 'Explotación de recursos', 56),
(165, 'Obras de ingeniería', 57),
(166, 'Delimitación de asentamientos', 57),
(167, 'Geotécnicos para obras', 57),
(168, 'Evaluación de riesgos', 58),
(169, 'Caracterización de suelos', 58),
(170, 'Riesgos geológicos', 58),
(171, 'Manejo', 59),
(172, 'Interpretación de bases', 59),
(173, 'Enfoque geoestadístico', 59),
(174, 'Análisis', 60),
(175, 'Implementación de sistemas', 60),
(176, 'Algoritmos de ia', 60),
(177, 'Procesamiento de lenguaje', 61),
(178, 'Visión artificial', 61),
(179, 'Modelos bioinspirados', 61),
(180, 'Desarrollo colaborativo', 62),
(181, 'Ciudades inteligentes', 62),
(182, 'Automatización', 62),
(183, 'Calidad', 63),
(184, 'Logística', 63),
(185, 'Cadenas de suministro', 63),
(186, 'Integración de tecnologías', 64),
(187, 'Manufactura avanzada', 64),
(188, 'Diseño de procesos', 64),
(189, 'Realización de experimentos', 65),
(190, 'Productos', 65),
(191, 'Procesos', 65),
(192, 'Bioestadística', 66),
(193, 'Modelos matemáticos predictivos', 66),
(194, 'Modelos matemáticos', 66),
(195, 'Implementación de software', 67),
(196, 'Internet', 67),
(197, 'Alta calidad', 67),
(198, 'Analítica de datos', 68),
(199, 'Gestión de gestión', 68),
(200, 'Dirección de proyectos', 69),
(201, 'Consultoría', 69),
(202, 'Emprendimiento', 69),
(203, 'Planteamiento', 70),
(204, 'Solución algorítmica', 70),
(205, 'Programación avanzada', 70),
(206, 'Análisis de datos', 71),
(207, 'Redes neuronales', 71),
(208, 'Modelos estocásticos', 71),
(209, 'Desarrollo de modelos', 72),
(210, 'Finanzas cuantitativas', 72),
(211, 'Matemáticos para finanzas', 72),
(212, 'Redacción científico-técnica', 73),
(213, 'Composición de textos', 73),
(214, 'Redacción científico', 73),
(215, 'Análisis de problemas', 74),
(216, 'Creación', 74),
(217, 'Solución', 74),
(218, 'Desarrollo de herramientas', 75),
(219, 'Solución de ecuaciones', 75),
(220, 'Computacionales para solución', 75),
(221, 'Administración de recursos', 76),
(222, 'Elaboración de estudios', 76),
(223, 'Facilitación del diálogo', 77),
(224, 'Integración', 77),
(225, 'Grupos interdisciplinarios', 77),
(226, 'Fabricación', 78),
(227, 'Mantenimiento de máquinas', 78),
(228, 'Sistemas mecánicos', 78),
(229, 'Marcha', 79),
(230, 'Industrias metal-mecánicas', 79),
(231, 'Puesta en marcha', 79),
(232, 'Optimización del aprovechamiento', 80),
(233, 'Industria', 80),
(234, 'Tipos de energía', 80),
(235, 'Dirección de micro', 81),
(236, 'Pequeñas', 81),
(237, 'Medianas empresas metal-mecánicas', 81),
(238, 'Integración de sistemas', 82),
(239, 'Sistemas mecatrónicos', 82),
(240, 'Desarrollo de hardware', 83),
(241, 'Manufactura asistida', 83),
(242, 'Software para control', 83),
(243, 'Integración de componentes', 84),
(244, 'Sensores', 84),
(245, 'Actuadores', 84),
(246, 'Modelado de sistemas', 85),
(247, 'Planteamiento de hipótesis', 85),
(248, 'Validación experimental', 85),
(249, 'Obtención', 86),
(250, 'Radares', 86),
(251, 'Satélites', 86),
(252, 'Elaboración de pronósticos', 87),
(253, 'Predicción numérica', 87),
(254, 'Emisión de alertas', 87),
(255, 'Desarrollo de software', 88),
(256, 'Modelos informáticos', 88),
(257, 'Procesamiento de datos', 88),
(258, 'Movilidad urbana', 89),
(259, 'Gestión de planeación,', 89),
(260, 'Articulación de soluciones', 90),
(261, 'Mercancías', 90),
(262, 'Dimensiones territorial', 90),
(263, 'Evaluación de proyectos', 91),
(264, 'Impacto social', 91),
(265, 'Infraestructura de transporte', 91),
(266, 'Manejo de software', 92),
(267, 'Hojas de cálculo', 92),
(268, 'Herramientas gráficas', 92),
(269, 'Gestión de modelos', 93),
(270, 'Proyectos', 93),
(271, 'Sector energético', 93),
(272, 'Evaluación de eficiencia', 94),
(273, 'Gestión sustentable', 94),
(274, 'Análisis de ciclo', 94),
(275, 'Diseño de estrategias', 95),
(276, 'Aprovechamiento de fuentes', 95),
(277, 'Económicas para aprovechamiento', 95),
(278, 'Desarrollo de habilidades', 96),
(279, 'Comunicación efectiva', 96),
(280, 'Negociación', 96),
(281, 'Dirección de procesos', 97),
(282, 'Extracción de hidrocarburos', 97),
(283, 'Energía geotérmica', 97),
(284, 'Programación', 98),
(285, 'Supervisión', 98),
(286, 'Mantenimiento de pozos', 98),
(287, 'Cuantificación de reservas', 99),
(288, 'Caracterización de yacimientos', 99),
(289, 'Simulación numérica', 99),
(290, 'Elaboración de análisis', 100),
(291, 'Licitación', 100),
(292, 'Factibilidad de proyectos', 100),
(293, 'Administración de plantas', 101),
(294, 'Industriales sustentables', 101),
(295, 'Plantas químicas', 101),
(296, 'Evaluación de operaciones', 102),
(297, 'Transformación', 102),
(298, 'Operaciones unitarias', 102),
(299, 'Modelado', 103),
(300, 'Optimización de procesos', 103),
(301, 'Procesos químicos', 103),
(302, 'Aplicación de sistemas', 104),
(303, 'Seguridad', 104),
(304, 'Higiene industrial', 104),
(305, 'Optimización de plantas', 105),
(306, 'Procesamiento de gas', 105),
(307, 'Refinación de petróleo', 105),
(308, 'Muestreo', 106),
(309, 'Caracterización', 106),
(310, 'Control de calidad', 106),
(311, 'Tratamiento estadístico', 107),
(312, 'Uso de simuladores', 107),
(313, 'Estadístico de datos', 107),
(314, 'Supervisión de medidas', 108),
(315, 'Control de contaminantes', 108),
(316, 'Mantenimiento de celdas', 109),
(317, 'Sistemas automatizados', 109),
(318, 'Equipos de producción', 109),
(319, 'Islas de manufactura', 110),
(320, 'Manufactura robotizadas', 110),
(321, 'Implementación', 111),
(322, 'Lenguajes de programación', 111),
(323, 'Tecnologías de automatización', 111),
(324, 'Prueba', 112),
(325, 'Sistemas automotrices', 112),
(326, 'Herramientas de ingeniería', 113),
(327, 'Diseño asistido', 113),
(328, 'Sector automotriz', 113),
(329, 'Ejecución de proyectos', 114),
(330, 'Ingeniería experimental', 114),
(331, 'Organización', 115),
(332, 'Supervisión de mantenimiento', 115),
(333, 'Producción industrial', 115),
(334, 'Estándares de calidad', 116),
(335, 'Gestión de modelado,', 116),
(336, 'Diseño de algoritmos', 117),
(337, 'Estructuras de datos', 117),
(338, 'Algoritmos eficientes', 117),
(339, 'Implementación de arquitecturas', 118),
(340, 'Sistemas distribuidos', 118),
(341, 'Protocolos de red', 118),
(342, 'Liderazgo de equipos', 119),
(343, 'Trabajo tecnológicos', 119),
(344, 'Monitoreo', 120),
(345, 'Gestión de redes', 120),
(346, 'Generación distribuida', 120),
(347, 'Optimización de recursos', 121),
(348, 'Mejoramiento de calidad', 121),
(349, 'Energéticos del lado', 121),
(350, 'Implementación de soluciones', 122),
(351, 'Infraestructura energética', 122),
(352, 'Ciberseguridad en infraestructura', 122),
(353, 'Administración', 123),
(354, 'Operación de redes', 123),
(355, 'Inalámbricas', 123),
(356, 'Cómputo ubicuo', 124),
(357, 'Desarrollo de aplicaciones', 124),
(358, 'Aplicaciones telemáticas', 124),
(359, 'Empleo de protocolos', 125),
(360, 'Transmisión segura', 125),
(361, 'Comunicación para transmisión', 125),
(362, 'Instalación', 126),
(363, 'Gestión de instalación', 126),
(364, 'Identificación', 127),
(365, 'Tejidos', 127),
(366, 'Prendas', 127),
(367, 'Estampado', 128),
(368, 'Acabado textil', 128),
(369, 'Químicos de tintura', 128),
(370, 'Aplicación de estudios', 129),
(371, 'Movimientos', 129),
(372, 'Metrología', 129),
(373, 'Ejecución de levantamientos', 130),
(374, 'Geodésicos', 130),
(375, 'Fotogramétricos', 130),
(376, 'Procesamiento digital', 131),
(377, 'Modelos digitales', 131),
(378, 'Digital de imágenes', 131),
(379, 'Operación de equipo', 132),
(380, 'Geodésico de precisión', 132),
(381, 'Catastro', 132),
(382, 'Evaluación de sistemas', 133),
(383, 'Transporte multimotriz', 133),
(384, 'Aplicación de tecnologías', 134),
(385, 'Planeación logística', 134),
(386, 'Control de flotas', 134),
(387, 'Análisis del impacto', 135),
(388, 'Económico', 135),
(389, 'Político', 135),
(390, 'Optimización de flotas', 136),
(391, 'Competencia HP136-2', 136),
(392, 'Desarrollo de análogos', 137),
(393, 'Dispositivos artificiales', 137),
(394, 'Sistemas biomiméticos', 137),
(395, 'Aplicación de principios', 138),
(396, 'Solución de problemas', 138),
(397, 'Principios biomiméticos', 138),
(398, 'Modelado matemático', 139),
(399, 'Simulación de variables', 139),
(400, 'Dinámicas', 139),
(401, 'Uso de bioestadística', 140),
(402, 'Matemáticas avanzadas', 140),
(403, 'Cálculo', 140),
(404, 'Localización', 141),
(405, 'Marcha de plantas', 141),
(406, 'Procesadoras de alimentos', 141),
(407, 'Inocuidad', 142),
(408, 'Almacenamiento', 142),
(409, 'Conservación', 142),
(410, 'Utilización de técnicas', 143),
(411, 'Escalamiento de productos', 143),
(412, 'Simulación para desarrollo', 143),
(413, 'Insumos', 144),
(414, 'Productos terminados', 144),
(415, 'Calidad de materias', 144),
(416, 'Diseño de sistemas', 145),
(417, 'Minimización', 145),
(418, 'Manejo de residuos', 146),
(419, 'Peligrosos', 146),
(420, 'Tratamiento de aguas', 146),
(421, 'Adaptación de tecnologías', 147),
(422, 'Restauración de sitios', 147),
(423, 'Sitios contaminados', 147),
(424, 'Implementación del uso', 148),
(425, 'Conservación ambiental', 148),
(426, 'Alternas para conservación', 148),
(427, 'Selección', 149),
(428, 'Desarrollo de métodos', 149),
(429, 'Diagnóstico microbiológico', 149),
(430, 'Producción', 150),
(431, 'Control integral', 150),
(432, 'Vacunas', 150),
(433, 'Manejo de microorganismos', 151),
(434, 'Condiciones asépticas', 151),
(435, 'Bioseguridad ambiental', 151),
(436, 'Análisis de relaciones', 152),
(437, 'Restauración', 152),
(438, 'Biorremediación', 152),
(439, 'Aprovechamiento sustentable', 153),
(440, 'Biodiversidad', 153),
(441, 'Sustentable de recursos', 153),
(442, 'Evaluaciones de impacto', 154),
(443, 'Auditorías', 154),
(444, 'Implementación de acciones', 154),
(445, 'Curaduría', 155),
(446, 'Gestión de colecciones', 155),
(447, 'Catálogos de recursos', 155),
(448, 'Análisis de procesos', 156),
(449, 'Genéticos', 156),
(450, 'Biotecnológicos', 156),
(451, 'Administración de equipos', 157),
(452, 'Instrumentos médicos hospitalarios', 157),
(453, 'Instrumentos médicos', 157),
(454, 'Desarrollo de biomateriales', 158),
(455, 'Prótesis', 158),
(456, 'Órtesis', 158),
(457, 'Generación de criterios', 159),
(458, 'Normatividad', 159),
(459, 'Infraestructura hospitalaria', 159),
(460, 'Gestión tecnológica', 160),
(461, 'Ingeniería clínica', 160),
(462, 'Investigación médica', 160),
(463, 'Aislamiento', 161),
(464, 'Purificación', 161),
(465, 'Cultivo', 161),
(466, 'Optimización de bioprocesos', 162),
(467, 'Recuperación de bioproductos', 162),
(468, 'Bioprocesos', 162),
(469, 'Inspección de muestras', 163),
(470, 'Técnicas físico-químicas', 163),
(471, 'Instrumentales avanzadas', 163),
(472, 'Control de bioprocesos', 164),
(473, 'Bioingeniería ambiental', 164),
(474, 'Tratamiento de efluentes', 164),
(475, 'Aplicación de biotecnología', 165),
(476, 'Sectores agropecuario', 165),
(477, 'Industrial', 165),
(478, 'Producción biotecnológica', 166),
(479, 'Medicamentos', 166),
(480, 'Alimentos fermentados', 166),
(481, 'Atención médica integral', 167),
(482, 'Prevención', 167),
(483, 'Tratamiento', 167),
(484, 'Investigación de problemas', 168),
(485, 'Desarrollo asistencial humanitario', 168),
(486, 'Salud pública', 168),
(487, 'Relación médico-paciente ética', 169),
(488, 'Responsable', 169),
(489, 'Solidaria', 169),
(490, 'Diagnóstico clínico', 170),
(491, 'Atención preventiva', 170),
(492, 'Curativa', 170),
(493, 'Atención del embarazo', 171),
(494, 'Puerperio', 171),
(495, 'Programas prioritarios', 171),
(496, 'Manejo farmacológico', 172),
(497, 'Interpretación de estudios', 172),
(498, 'Imagenología médica', 172),
(499, 'Compromiso ético', 173),
(500, 'Humanístico', 173),
(501, 'Bioética', 173),
(502, 'Cuidado integral', 174),
(503, 'Atención de salud', 174),
(504, 'Perinatal', 174),
(505, 'Fomento del autocuidado', 175),
(506, 'Estilos de vida', 175),
(507, 'Educación', 175),
(508, 'Aplicación del método', 176),
(509, 'Primer', 176),
(510, 'Segundo', 176),
(511, 'Sensibilidad social', 177),
(512, 'Ética humanística', 177),
(513, 'Cuidado', 177),
(514, 'Promoción', 178),
(515, 'Recuperación', 178),
(516, 'Método enfermero', 178),
(517, 'Ejecución de intervenciones', 179),
(518, 'Cuidado holístico', 179),
(519, 'Administración estratégica', 180),
(520, 'Investigación clínica', 180),
(521, 'Estratégica de servicios', 180),
(522, 'Actitud ética', 181),
(523, 'Humanística', 181),
(524, 'Respeto', 181),
(525, 'Producción de medicamentos', 182),
(526, 'Gestión de diseño,', 182),
(527, 'Aplicación de procesos', 183),
(528, 'Formulación farmacéutica', 183),
(529, 'Uso humano', 183),
(530, 'Aplicación de conocimientos', 184),
(531, 'Proteómica', 184),
(532, 'Genómica', 184),
(533, 'Sistemas de entrega', 185),
(534, 'Competencia HP185-2', 185),
(535, 'Atención', 186),
(536, 'Farmacia industrial', 186),
(537, 'Hospitalaria', 186),
(538, 'Gestión de calidad', 187),
(539, 'Cumplimiento de buenas', 187),
(540, 'Prácticas de fabricación', 187),
(541, 'Evaluación del estado', 188),
(542, 'Cálculo dietoterapéutico individual', 188),
(543, 'Comunitario', 188),
(544, 'Evaluación de programas', 189),
(545, 'Nutrición aplicada', 189),
(546, 'Servicios institucionales', 190),
(547, 'Sanitaria en servicios', 190),
(548, 'Institucionales de alimentos', 190),
(549, 'Orientación alimentaria', 191),
(550, 'Diversos grupos', 191),
(551, 'Grupos de edad', 191),
(552, 'Rehabilitación integral', 192),
(553, 'Salud bucodental', 192),
(554, 'Operatoria dental', 193),
(555, 'Endodoncia', 193),
(556, 'Exodoncia', 193),
(557, 'Manejo de materiales', 194),
(558, 'Bioseguridad', 194),
(559, 'Radiología intraoral', 194),
(560, 'Desarrollo de proyectos', 195),
(561, 'Epidemiológica', 195),
(562, 'Odontología', 195),
(563, 'Tratamiento de alteraciones', 196),
(564, 'Salud visual', 196),
(565, 'Alteraciones refractivas', 196),
(566, 'Prescripción', 197),
(567, 'Adaptación de ayudas', 197),
(568, 'Lentes de contacto', 197),
(569, 'Ejecución de campañas', 198),
(570, 'Diagnóstico epidemiológico ocular', 198),
(571, 'Diagnóstico epidemiológico', 198),
(572, 'Integración de ciencias', 199),
(573, 'Instrumental optométrico', 199),
(574, 'Ciencias biomédicas', 199),
(575, 'Evaluación de estados', 200),
(576, 'Personalidad', 200),
(577, 'Competencias cognitivas', 200),
(578, 'Clínica', 201),
(579, 'Organizaciones', 201),
(580, 'Psicológicas en clínica', 201),
(581, 'Promoción del bienestar', 202),
(582, 'Grupal', 202),
(583, 'Bienestar psicológico', 202),
(584, 'Investigación científica', 203),
(585, 'Procesos bio-psico-sociales', 203),
(586, 'Científica del comportamiento', 203),
(587, 'Diagnóstico de vulnerabilidad', 204),
(588, 'Auditoría de riesgos', 204),
(589, 'Vulnerabilidad ambiental', 204),
(590, 'Acondicionamiento hídrico', 205),
(591, 'Tratamiento de agua', 205),